security:
    providers:
        main:
            entity:
                class:    AppBundle:User
                property: steamid

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:   ^/
            security:  true
            anonymous: true
            stateless: false
